# Generated by Django 3.2.9 on 2023-02-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_HV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencies',
            name='boss',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='experiencies',
            name='position_boss',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
