# Generated by Django 3.2.9 on 2023-02-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_HV', '0002_auto_20230219_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección o ubicación'),
        ),
    ]
