# Generated by Django 3.2.9 on 2023-02-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_HV', '0003_projects_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencies',
            name='boss',
        ),
        migrations.AddField(
            model_name='experiencies',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='fields/certificate', verbose_name='Adjuntar certificado'),
        ),
        migrations.AlterField(
            model_name='languages_programing',
            name='level',
            field=models.CharField(choices=[('Basico', 'Basico'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=50, verbose_name='Nivel de progreso'),
        ),
        migrations.AlterField(
            model_name='profesional_education',
            name='diploma',
            field=models.FileField(blank=True, null=True, upload_to='fields/diploma', verbose_name='Adjuntar diploma'),
        ),
        migrations.AlterField(
            model_name='profesional_education',
            name='type_estudy',
            field=models.CharField(choices=[('Curso', 'Curso'), ('Diplomado', 'Diplomado'), ('Bachillerato', 'Bachillerato'), ('Tecnico', 'Tecnico'), ('Tecnologo', 'Tecnologo'), ('Profesional', 'Profesional'), ('Especialización', 'Especialización'), ('Maestria', 'Maestria'), ('Doctorado', 'Doctorado'), ('Posdoctorado', 'Posdoctorado')], max_length=75, verbose_name='Tipo de estudio'),
        ),
    ]
