# Generated by Django 3.2.9 on 2023-02-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_HV', '0005_alter_languages_programing_have_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='basic_data_change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Bogotá', 'Bogotá'), ('Tauramena - Casanare', 'Tauramenta - Casanare')], max_length=75, verbose_name='Ciudad o municipio')),
                ('address', models.CharField(choices=[('Calle 69 Bis # 111 A - 46', 'Calle 69 Bis # 111 A - 46'), ('Calle 12 # 10 - 15', 'Calle 12 # 10 - 15')], max_length=50, verbose_name='Dirección')),
            ],
        ),
        migrations.AlterField(
            model_name='experiencies',
            name='position_boss',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Titulo de jefe'),
        ),
        migrations.AlterField(
            model_name='languages_programing',
            name='class_icon',
            field=models.CharField(max_length=200, verbose_name='Clase del lenguaje o enlace'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='tecnologias',
            field=models.ManyToManyField(to='gestion_HV.languages_programing', verbose_name='Tecnologias utilizadas'),
        ),
    ]
